# Deployment for backend API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: safeshipping
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: safeshipping/backend-api:latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: BLOCKCHAIN_NODE_URL
          value: "http://blockchain-node:8545"
        - name: ORACLE_SERVICE_URL
          value: "http://oracle-service:3000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-secret
        ports:
        - containerPort: 4000
          name: http
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 20
          periodSeconds: 15
      volumes:
      - name: config-volume
        configMap:
          name: backend-api-config