# PersistentVolumeClaim for blockchain data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethereum-data-pvc
  namespace: safeshipping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard